### ISSUE TITLE
shell tool: bad/unsafe binary name

### ISSUE THREAD

**Issue by draeath** [willroberts/minecraft-client-rs#7]
Just wanted to drop a comment. I am looking to utilize this to automate a safe shutdown via a service manager. I got caught out by the name `shell` landing in path when doing a `cargo install --all-features` replacing an actual `shell` command on the system.

Please consider changing the name of this artifact.

(not a huge deal, I can just rename it or use `--root` to put it somewhere else and symlink it with a different name)

**Comment by willroberts** [comment]
Hi, thanks for the report! This has been fixed in #8. The new executable name is `minecraft-cli`.
