### ISSUE TITLE
close on drop

### ISSUE THREAD

**Issue by abnormal-coffee** [willroberts/minecraft-client-rs#9]
The example usage suggests client.close() to cleanly close the connection at the end of the program, would it make sense to implement Drop for Client such that the client is autoclosed upon the variable being dropped? 
Something like this:```
impl Drop for Client {
    fn drop(&mut self) {
        self.drop();
    }
}```

**Comment by willroberts** [comment]
This is a good idea!

Feel free to open a PR for this; otherwise I'll get around to it a little later on.

**Comment by abnormal-coffee** [comment]
I have created a PR.
